runtime: python312
instance_class: F1
app_engine_apis: true
automatic_scaling:
  min_instances: 0
  max_instances: 1

env_variables:
  AUTH_DOMAIN: 'gmail.com'

handlers:
- url: /.*
  secure: always
  script: auto
